// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAnnounce = "announce"

// Announce mapped from table <announce>
type Announce struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Found       bool      `gorm:"column:found;type:boolean;not null;index:idx_announce_found,priority:1" json:"found"`
	Title       string    `gorm:"column:title;type:character varying(256);not null;default:''::character varying" json:"title"`
	Date        time.Time `gorm:"column:date;type:date;not null;index:idx_announce_date,priority:1;default:0001-01-01" json:"date"`
	Context     string    `gorm:"column:context;type:text;not null" json:"context"`
	Content     string    `gorm:"column:content;type:text;not null" json:"content"`
	Attachments string    `gorm:"column:attachments;type:jsonb;not null" json:"attachments"`
	CreateTime  time.Time `gorm:"column:create_time;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
}

// TableName Announce's table name
func (*Announce) TableName() string {
	return TableNameAnnounce
}
