// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttachment = "attachment"

// Attachment mapped from table <attachment>
type Attachment struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	URL          string    `gorm:"column:url;type:character varying(512);not null;uniqueIndex:idx_attachment_url,priority:1;default:''::character varying" json:"url"`
	Name         string    `gorm:"column:name;type:character varying(256);not null;default:''::character varying" json:"name"`
	Size         int64     `gorm:"column:size;type:bigint;not null" json:"size"`
	Type         string    `gorm:"column:type;type:character varying(64);not null;default:''::character varying" json:"type"`
	Sha256       string    `gorm:"column:sha256;type:character(64);not null;uniqueIndex:idx_attachment_sha256,priority:1;default:''::bpchar" json:"sha256"`
	Content      string    `gorm:"column:content;type:text;not null" json:"content"`
	LastModified int64     `gorm:"column:last_modified;type:bigint;not null" json:"last_modified"`
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
}

// TableName Attachment's table name
func (*Attachment) TableName() string {
	return TableNameAttachment
}
