// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBbsPost = "bbs_post"

// BbsPost mapped from table <bbs_post>
type BbsPost struct {
	ID         int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:帖子ID" json:"id"`                                                         // 帖子ID
	Code       int32     `gorm:"column:code;type:int;not null;index:idx_code,priority:1;comment:状态码" json:"code"`                                                             // 状态码
	Message    string    `gorm:"column:message;type:varchar(255);not null;comment:状态信息" json:"message"`                                                                       // 状态信息
	Success    bool      `gorm:"column:success;type:tinyint(1);not null;comment:是否成功" json:"success"`                                                                         // 是否成功
	Data       string    `gorm:"column:data;type:json;not null;comment:数据" json:"data"`                                                                                       // 数据
	CreateTime time.Time `gorm:"column:create_time;type:timestamp(3);not null;index:idx_create_time,priority:1;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp(3);not null;index:idx_update_time,priority:1;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_time"` // 更新时间
}

// TableName BbsPost's table name
func (*BbsPost) TableName() string {
	return TableNameBbsPost
}
