// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBbsPost = "bbs_post"

// BbsPost mapped from table <bbs_post>
type BbsPost struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Code       int32     `gorm:"column:code;type:integer;not null;index:idx_bbs_post_code,priority:1" json:"code"`
	Message    string    `gorm:"column:message;type:character varying(256);not null;default:''::character varying" json:"message"`
	Success    bool      `gorm:"column:success;type:boolean;not null" json:"success"`
	Data       string    `gorm:"column:data;type:jsonb;not null" json:"data"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp(3) with time zone;not null;index:idx_bbs_post_create_time,priority:1;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp(3) with time zone;not null;index:idx_bbs_post_update_time,priority:1;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
}

// TableName BbsPost's table name
func (*BbsPost) TableName() string {
	return TableNameBbsPost
}
