// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBbsPostItem = "bbs_post_item"

// BbsPostItem mapped from table <bbs_post_item>
type BbsPostItem struct {
	ID             int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:帖子ID" json:"id"`                                                         // 帖子ID
	History        bool      `gorm:"column:history;type:tinyint(1);not null;index:idx_history,priority:1;comment:历史" json:"history"`                                              // 历史
	Official       bool      `gorm:"column:official;type:tinyint(1);not null;index:idx_official,priority:1;comment:官方" json:"official"`                                           // 官方
	Top            bool      `gorm:"column:top;type:tinyint(1);not null;index:idx_top,priority:1;comment:置顶" json:"top"`                                                          // 置顶
	Marrow         bool      `gorm:"column:marrow;type:tinyint(1);not null;index:idx_marrow,priority:1;comment:精华" json:"marrow"`                                                 // 精华
	HeadImg        string    `gorm:"column:head_img;type:text;not null;comment:头像" json:"head_img"`                                                                               // 头像
	Category       string    `gorm:"column:category;type:varchar(64);not null;index:idx_category,priority:1;comment:分类" json:"category"`                                          // 分类
	CategoryDesc   string    `gorm:"column:category_desc;type:varchar(256);not null;comment:分类描述" json:"category_desc"`                                                           // 分类描述
	Title          string    `gorm:"column:title;type:varchar(256);not null;comment:标题" json:"title"`                                                                             // 标题
	Introduction   string    `gorm:"column:introduction;type:text;not null;comment:简介" json:"introduction"`                                                                       // 简介
	AuthorID       int64     `gorm:"column:author_id;type:bigint unsigned;not null;index:idx_author_id,priority:1;comment:作者ID" json:"author_id"`                                 // 作者ID
	AuthorNickname string    `gorm:"column:author_nickname;type:varchar(64);not null;comment:作者昵称" json:"author_nickname"`                                                        // 作者昵称
	AuthorAvatar   string    `gorm:"column:author_avatar;type:varchar(256);not null;comment:作者头像" json:"author_avatar"`                                                           // 作者头像
	CreateAt       time.Time `gorm:"column:create_at;type:timestamp(3);not null;index:idx_create_at,priority:1;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_at"`       // 创建时间
	Views          int64     `gorm:"column:views;type:bigint unsigned;not null;index:idx_views,priority:1;comment:浏览数" json:"views"`                                              // 浏览数
	Approvals      int64     `gorm:"column:approvals;type:bigint unsigned;not null;index:idx_approvals,priority:1;comment:点赞数" json:"approvals"`                                  // 点赞数
	Comments       int64     `gorm:"column:comments;type:bigint unsigned;not null;index:idx_comments,priority:1;comment:评论数" json:"comments"`                                     // 评论数
	Tags           string    `gorm:"column:tags;type:json;not null;comment:标签" json:"tags"`                                                                                       // 标签
	Solution       string    `gorm:"column:solution;type:json;not null;comment:解决方案" json:"solution"`                                                                             // 解决方案
	SolutionDesc   string    `gorm:"column:solution_desc;type:varchar(512);not null;comment:解决方案描述" json:"solution_desc"`                                                         // 解决方案描述
	State          string    `gorm:"column:state;type:varchar(64);not null;index:idx_state,priority:1;comment:状态" json:"state"`                                                   // 状态
	StateDesc      string    `gorm:"column:state_desc;type:varchar(256);not null;comment:状态描述" json:"state_desc"`                                                                 // 状态描述
	UpdateAt       time.Time `gorm:"column:update_at;type:timestamp(3);not null;index:idx_update_at,priority:1;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_at"`       // 更新时间
	WikiID         int64     `gorm:"column:wiki_id;type:bigint unsigned;not null;index:idx_wiki_id,priority:1;comment:WikiID" json:"wiki_id"`                                     // WikiID
	CreateTime     time.Time `gorm:"column:create_time;type:timestamp(3);not null;index:idx_create_time,priority:1;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;type:timestamp(3);not null;index:idx_update_time,priority:1;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_time"` // 更新时间
}

// TableName BbsPostItem's table name
func (*BbsPostItem) TableName() string {
	return TableNameBbsPostItem
}
