// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSearchLog = "search_log"

// SearchLog mapped from table <search_log>
type SearchLog struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RemoteIP       string    `gorm:"column:remote_ip;type:character(39);not null;index:idx_search_log_remote_ip,priority:1;default:''::bpchar" json:"remote_ip"`
	UserAgent      string    `gorm:"column:user_agent;type:character varying(512);not null;default:''::character varying" json:"user_agent"`
	RequestBody    string    `gorm:"column:request_body;type:text;not null" json:"request_body"`
	RequestLength  int32     `gorm:"column:request_length;type:integer;not null;index:idx_search_log_request_length,priority:1" json:"request_length"`
	Query          string    `gorm:"column:query;type:character varying(256);not null;index:idx_search_log_query,priority:1;default:''::character varying" json:"query"`
	Status         int32     `gorm:"column:status;type:integer;not null;index:idx_search_log_status,priority:1" json:"status"`
	ResponseBody   string    `gorm:"column:response_body;type:text;not null" json:"response_body"`
	ResponseLength int32     `gorm:"column:response_length;type:integer;not null;index:idx_search_log_response_length,priority:1" json:"response_length"`
	Latency        int32     `gorm:"column:latency;type:integer;not null;index:idx_search_log_latency,priority:1" json:"latency"`
	CreateTime     time.Time `gorm:"column:create_time;type:timestamp(3) with time zone;not null;index:idx_search_log_create_time,priority:1;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
}

// TableName SearchLog's table name
func (*SearchLog) TableName() string {
	return TableNameSearchLog
}
