DataSource: "host=DB_HOST port=5432 user=postgres password=DB_PASSWORD dbname=rm_search sslmode=disable"
MeiliSearch:
  Address: "http://localhost:7700"
  APIKey: "MEILI_MASTER_KEY"
TikaHost: "http://localhost:9998"
SearchLog:
  Enabled: true
  DisabledRequestBody: false
  DisabledResponseBody: false
Proxy:
  Enabled: false
  URL: "http://localhost:7890"
DJIMetaKey: "DJI_META_KEY"
