networks:
  default:
    external: false

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    networks:
      - default
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.17.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_PASSWORD=elastic
      - KIBANA_PASSWORD=kibana
      - "discovery.type=single-node"
      - "_JAVA_OPTIONS=-XX:UseSVE=0"
      - "xpack.security.enabled=false"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - default
  kibana:
    container_name: kibana
    image: kibana:8.17.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
    networks:
      - default