// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/scutrobotlab/rm-search/database/model"
)

func newAnnounce(db *gorm.DB, opts ...gen.DOOption) announce {
	_announce := announce{}

	_announce.announceDo.UseDB(db, opts...)
	_announce.announceDo.UseModel(&model.Announce{})

	tableName := _announce.announceDo.TableName()
	_announce.ALL = field.NewAsterisk(tableName)
	_announce.ID = field.NewInt64(tableName, "id")
	_announce.Found = field.NewBool(tableName, "found")
	_announce.Title = field.NewString(tableName, "title")
	_announce.Date = field.NewTime(tableName, "date")
	_announce.Context = field.NewString(tableName, "context")
	_announce.Content = field.NewString(tableName, "content")
	_announce.Attaches = field.NewString(tableName, "attaches")
	_announce.CreateTime = field.NewTime(tableName, "create_time")
	_announce.UpdateTime = field.NewTime(tableName, "update_time")

	_announce.fillFieldMap()

	return _announce
}

type announce struct {
	announceDo

	ALL        field.Asterisk
	ID         field.Int64  // 公告ID
	Found      field.Bool   // 是否找到
	Title      field.String // 标题
	Date       field.Time   // 日期
	Context    field.String // 上下文
	Content    field.String // 内容
	Attaches   field.String // 附件
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a announce) Table(newTableName string) *announce {
	a.announceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a announce) As(alias string) *announce {
	a.announceDo.DO = *(a.announceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *announce) updateTableName(table string) *announce {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Found = field.NewBool(table, "found")
	a.Title = field.NewString(table, "title")
	a.Date = field.NewTime(table, "date")
	a.Context = field.NewString(table, "context")
	a.Content = field.NewString(table, "content")
	a.Attaches = field.NewString(table, "attaches")
	a.CreateTime = field.NewTime(table, "create_time")
	a.UpdateTime = field.NewTime(table, "update_time")

	a.fillFieldMap()

	return a
}

func (a *announce) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *announce) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["found"] = a.Found
	a.fieldMap["title"] = a.Title
	a.fieldMap["date"] = a.Date
	a.fieldMap["context"] = a.Context
	a.fieldMap["content"] = a.Content
	a.fieldMap["attaches"] = a.Attaches
	a.fieldMap["create_time"] = a.CreateTime
	a.fieldMap["update_time"] = a.UpdateTime
}

func (a announce) clone(db *gorm.DB) announce {
	a.announceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a announce) replaceDB(db *gorm.DB) announce {
	a.announceDo.ReplaceDB(db)
	return a
}

type announceDo struct{ gen.DO }

type IAnnounceDo interface {
	gen.SubQuery
	Debug() IAnnounceDo
	WithContext(ctx context.Context) IAnnounceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAnnounceDo
	WriteDB() IAnnounceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAnnounceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAnnounceDo
	Not(conds ...gen.Condition) IAnnounceDo
	Or(conds ...gen.Condition) IAnnounceDo
	Select(conds ...field.Expr) IAnnounceDo
	Where(conds ...gen.Condition) IAnnounceDo
	Order(conds ...field.Expr) IAnnounceDo
	Distinct(cols ...field.Expr) IAnnounceDo
	Omit(cols ...field.Expr) IAnnounceDo
	Join(table schema.Tabler, on ...field.Expr) IAnnounceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAnnounceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAnnounceDo
	Group(cols ...field.Expr) IAnnounceDo
	Having(conds ...gen.Condition) IAnnounceDo
	Limit(limit int) IAnnounceDo
	Offset(offset int) IAnnounceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAnnounceDo
	Unscoped() IAnnounceDo
	Create(values ...*model.Announce) error
	CreateInBatches(values []*model.Announce, batchSize int) error
	Save(values ...*model.Announce) error
	First() (*model.Announce, error)
	Take() (*model.Announce, error)
	Last() (*model.Announce, error)
	Find() ([]*model.Announce, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Announce, err error)
	FindInBatches(result *[]*model.Announce, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Announce) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAnnounceDo
	Assign(attrs ...field.AssignExpr) IAnnounceDo
	Joins(fields ...field.RelationField) IAnnounceDo
	Preload(fields ...field.RelationField) IAnnounceDo
	FirstOrInit() (*model.Announce, error)
	FirstOrCreate() (*model.Announce, error)
	FindByPage(offset int, limit int) (result []*model.Announce, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAnnounceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a announceDo) Debug() IAnnounceDo {
	return a.withDO(a.DO.Debug())
}

func (a announceDo) WithContext(ctx context.Context) IAnnounceDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a announceDo) ReadDB() IAnnounceDo {
	return a.Clauses(dbresolver.Read)
}

func (a announceDo) WriteDB() IAnnounceDo {
	return a.Clauses(dbresolver.Write)
}

func (a announceDo) Session(config *gorm.Session) IAnnounceDo {
	return a.withDO(a.DO.Session(config))
}

func (a announceDo) Clauses(conds ...clause.Expression) IAnnounceDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a announceDo) Returning(value interface{}, columns ...string) IAnnounceDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a announceDo) Not(conds ...gen.Condition) IAnnounceDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a announceDo) Or(conds ...gen.Condition) IAnnounceDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a announceDo) Select(conds ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a announceDo) Where(conds ...gen.Condition) IAnnounceDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a announceDo) Order(conds ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a announceDo) Distinct(cols ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a announceDo) Omit(cols ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a announceDo) Join(table schema.Tabler, on ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a announceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a announceDo) RightJoin(table schema.Tabler, on ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a announceDo) Group(cols ...field.Expr) IAnnounceDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a announceDo) Having(conds ...gen.Condition) IAnnounceDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a announceDo) Limit(limit int) IAnnounceDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a announceDo) Offset(offset int) IAnnounceDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a announceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAnnounceDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a announceDo) Unscoped() IAnnounceDo {
	return a.withDO(a.DO.Unscoped())
}

func (a announceDo) Create(values ...*model.Announce) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a announceDo) CreateInBatches(values []*model.Announce, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a announceDo) Save(values ...*model.Announce) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a announceDo) First() (*model.Announce, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Announce), nil
	}
}

func (a announceDo) Take() (*model.Announce, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Announce), nil
	}
}

func (a announceDo) Last() (*model.Announce, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Announce), nil
	}
}

func (a announceDo) Find() ([]*model.Announce, error) {
	result, err := a.DO.Find()
	return result.([]*model.Announce), err
}

func (a announceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Announce, err error) {
	buf := make([]*model.Announce, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a announceDo) FindInBatches(result *[]*model.Announce, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a announceDo) Attrs(attrs ...field.AssignExpr) IAnnounceDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a announceDo) Assign(attrs ...field.AssignExpr) IAnnounceDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a announceDo) Joins(fields ...field.RelationField) IAnnounceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a announceDo) Preload(fields ...field.RelationField) IAnnounceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a announceDo) FirstOrInit() (*model.Announce, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Announce), nil
	}
}

func (a announceDo) FirstOrCreate() (*model.Announce, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Announce), nil
	}
}

func (a announceDo) FindByPage(offset int, limit int) (result []*model.Announce, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a announceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a announceDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a announceDo) Delete(models ...*model.Announce) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *announceDo) withDO(do gen.Dao) *announceDo {
	a.DO = *do.(*gen.DO)
	return a
}
