// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/scutrobotlab/rm-search/database/model"
)

func newBbsPostItem(db *gorm.DB, opts ...gen.DOOption) bbsPostItem {
	_bbsPostItem := bbsPostItem{}

	_bbsPostItem.bbsPostItemDo.UseDB(db, opts...)
	_bbsPostItem.bbsPostItemDo.UseModel(&model.BbsPostItem{})

	tableName := _bbsPostItem.bbsPostItemDo.TableName()
	_bbsPostItem.ALL = field.NewAsterisk(tableName)
	_bbsPostItem.ID = field.NewInt64(tableName, "id")
	_bbsPostItem.History = field.NewBool(tableName, "history")
	_bbsPostItem.Official = field.NewBool(tableName, "official")
	_bbsPostItem.Top = field.NewBool(tableName, "top")
	_bbsPostItem.Marrow = field.NewBool(tableName, "marrow")
	_bbsPostItem.HeadImg = field.NewString(tableName, "head_img")
	_bbsPostItem.Category = field.NewString(tableName, "category")
	_bbsPostItem.CategoryDesc = field.NewString(tableName, "category_desc")
	_bbsPostItem.Title = field.NewString(tableName, "title")
	_bbsPostItem.Introduction = field.NewString(tableName, "introduction")
	_bbsPostItem.AuthorID = field.NewInt64(tableName, "author_id")
	_bbsPostItem.AuthorNickname = field.NewString(tableName, "author_nickname")
	_bbsPostItem.AuthorAvatar = field.NewString(tableName, "author_avatar")
	_bbsPostItem.CreateAt = field.NewTime(tableName, "create_at")
	_bbsPostItem.Views = field.NewInt64(tableName, "views")
	_bbsPostItem.Approvals = field.NewInt64(tableName, "approvals")
	_bbsPostItem.Comments = field.NewInt64(tableName, "comments")
	_bbsPostItem.Tags = field.NewString(tableName, "tags")
	_bbsPostItem.Solution = field.NewString(tableName, "solution")
	_bbsPostItem.SolutionDesc = field.NewString(tableName, "solution_desc")
	_bbsPostItem.State = field.NewString(tableName, "state")
	_bbsPostItem.StateDesc = field.NewString(tableName, "state_desc")
	_bbsPostItem.UpdateAt = field.NewTime(tableName, "update_at")
	_bbsPostItem.WikiID = field.NewInt64(tableName, "wiki_id")
	_bbsPostItem.CreateTime = field.NewTime(tableName, "create_time")
	_bbsPostItem.UpdateTime = field.NewTime(tableName, "update_time")

	_bbsPostItem.fillFieldMap()

	return _bbsPostItem
}

type bbsPostItem struct {
	bbsPostItemDo

	ALL            field.Asterisk
	ID             field.Int64  // 帖子ID
	History        field.Bool   // 历史
	Official       field.Bool   // 官方
	Top            field.Bool   // 置顶
	Marrow         field.Bool   // 精华
	HeadImg        field.String // 头像
	Category       field.String // 分类
	CategoryDesc   field.String // 分类描述
	Title          field.String // 标题
	Introduction   field.String // 简介
	AuthorID       field.Int64  // 作者ID
	AuthorNickname field.String // 作者昵称
	AuthorAvatar   field.String // 作者头像
	CreateAt       field.Time   // 创建时间
	Views          field.Int64  // 浏览数
	Approvals      field.Int64  // 点赞数
	Comments       field.Int64  // 评论数
	Tags           field.String // 标签
	Solution       field.String // 解决方案
	SolutionDesc   field.String // 解决方案描述
	State          field.String // 状态
	StateDesc      field.String // 状态描述
	UpdateAt       field.Time   // 更新时间
	WikiID         field.Int64  // WikiID
	CreateTime     field.Time   // 创建时间
	UpdateTime     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bbsPostItem) Table(newTableName string) *bbsPostItem {
	b.bbsPostItemDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bbsPostItem) As(alias string) *bbsPostItem {
	b.bbsPostItemDo.DO = *(b.bbsPostItemDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bbsPostItem) updateTableName(table string) *bbsPostItem {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.History = field.NewBool(table, "history")
	b.Official = field.NewBool(table, "official")
	b.Top = field.NewBool(table, "top")
	b.Marrow = field.NewBool(table, "marrow")
	b.HeadImg = field.NewString(table, "head_img")
	b.Category = field.NewString(table, "category")
	b.CategoryDesc = field.NewString(table, "category_desc")
	b.Title = field.NewString(table, "title")
	b.Introduction = field.NewString(table, "introduction")
	b.AuthorID = field.NewInt64(table, "author_id")
	b.AuthorNickname = field.NewString(table, "author_nickname")
	b.AuthorAvatar = field.NewString(table, "author_avatar")
	b.CreateAt = field.NewTime(table, "create_at")
	b.Views = field.NewInt64(table, "views")
	b.Approvals = field.NewInt64(table, "approvals")
	b.Comments = field.NewInt64(table, "comments")
	b.Tags = field.NewString(table, "tags")
	b.Solution = field.NewString(table, "solution")
	b.SolutionDesc = field.NewString(table, "solution_desc")
	b.State = field.NewString(table, "state")
	b.StateDesc = field.NewString(table, "state_desc")
	b.UpdateAt = field.NewTime(table, "update_at")
	b.WikiID = field.NewInt64(table, "wiki_id")
	b.CreateTime = field.NewTime(table, "create_time")
	b.UpdateTime = field.NewTime(table, "update_time")

	b.fillFieldMap()

	return b
}

func (b *bbsPostItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bbsPostItem) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 26)
	b.fieldMap["id"] = b.ID
	b.fieldMap["history"] = b.History
	b.fieldMap["official"] = b.Official
	b.fieldMap["top"] = b.Top
	b.fieldMap["marrow"] = b.Marrow
	b.fieldMap["head_img"] = b.HeadImg
	b.fieldMap["category"] = b.Category
	b.fieldMap["category_desc"] = b.CategoryDesc
	b.fieldMap["title"] = b.Title
	b.fieldMap["introduction"] = b.Introduction
	b.fieldMap["author_id"] = b.AuthorID
	b.fieldMap["author_nickname"] = b.AuthorNickname
	b.fieldMap["author_avatar"] = b.AuthorAvatar
	b.fieldMap["create_at"] = b.CreateAt
	b.fieldMap["views"] = b.Views
	b.fieldMap["approvals"] = b.Approvals
	b.fieldMap["comments"] = b.Comments
	b.fieldMap["tags"] = b.Tags
	b.fieldMap["solution"] = b.Solution
	b.fieldMap["solution_desc"] = b.SolutionDesc
	b.fieldMap["state"] = b.State
	b.fieldMap["state_desc"] = b.StateDesc
	b.fieldMap["update_at"] = b.UpdateAt
	b.fieldMap["wiki_id"] = b.WikiID
	b.fieldMap["create_time"] = b.CreateTime
	b.fieldMap["update_time"] = b.UpdateTime
}

func (b bbsPostItem) clone(db *gorm.DB) bbsPostItem {
	b.bbsPostItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bbsPostItem) replaceDB(db *gorm.DB) bbsPostItem {
	b.bbsPostItemDo.ReplaceDB(db)
	return b
}

type bbsPostItemDo struct{ gen.DO }

type IBbsPostItemDo interface {
	gen.SubQuery
	Debug() IBbsPostItemDo
	WithContext(ctx context.Context) IBbsPostItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBbsPostItemDo
	WriteDB() IBbsPostItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBbsPostItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBbsPostItemDo
	Not(conds ...gen.Condition) IBbsPostItemDo
	Or(conds ...gen.Condition) IBbsPostItemDo
	Select(conds ...field.Expr) IBbsPostItemDo
	Where(conds ...gen.Condition) IBbsPostItemDo
	Order(conds ...field.Expr) IBbsPostItemDo
	Distinct(cols ...field.Expr) IBbsPostItemDo
	Omit(cols ...field.Expr) IBbsPostItemDo
	Join(table schema.Tabler, on ...field.Expr) IBbsPostItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBbsPostItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBbsPostItemDo
	Group(cols ...field.Expr) IBbsPostItemDo
	Having(conds ...gen.Condition) IBbsPostItemDo
	Limit(limit int) IBbsPostItemDo
	Offset(offset int) IBbsPostItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBbsPostItemDo
	Unscoped() IBbsPostItemDo
	Create(values ...*model.BbsPostItem) error
	CreateInBatches(values []*model.BbsPostItem, batchSize int) error
	Save(values ...*model.BbsPostItem) error
	First() (*model.BbsPostItem, error)
	Take() (*model.BbsPostItem, error)
	Last() (*model.BbsPostItem, error)
	Find() ([]*model.BbsPostItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BbsPostItem, err error)
	FindInBatches(result *[]*model.BbsPostItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BbsPostItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBbsPostItemDo
	Assign(attrs ...field.AssignExpr) IBbsPostItemDo
	Joins(fields ...field.RelationField) IBbsPostItemDo
	Preload(fields ...field.RelationField) IBbsPostItemDo
	FirstOrInit() (*model.BbsPostItem, error)
	FirstOrCreate() (*model.BbsPostItem, error)
	FindByPage(offset int, limit int) (result []*model.BbsPostItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBbsPostItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bbsPostItemDo) Debug() IBbsPostItemDo {
	return b.withDO(b.DO.Debug())
}

func (b bbsPostItemDo) WithContext(ctx context.Context) IBbsPostItemDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bbsPostItemDo) ReadDB() IBbsPostItemDo {
	return b.Clauses(dbresolver.Read)
}

func (b bbsPostItemDo) WriteDB() IBbsPostItemDo {
	return b.Clauses(dbresolver.Write)
}

func (b bbsPostItemDo) Session(config *gorm.Session) IBbsPostItemDo {
	return b.withDO(b.DO.Session(config))
}

func (b bbsPostItemDo) Clauses(conds ...clause.Expression) IBbsPostItemDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bbsPostItemDo) Returning(value interface{}, columns ...string) IBbsPostItemDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bbsPostItemDo) Not(conds ...gen.Condition) IBbsPostItemDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bbsPostItemDo) Or(conds ...gen.Condition) IBbsPostItemDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bbsPostItemDo) Select(conds ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bbsPostItemDo) Where(conds ...gen.Condition) IBbsPostItemDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bbsPostItemDo) Order(conds ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bbsPostItemDo) Distinct(cols ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bbsPostItemDo) Omit(cols ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bbsPostItemDo) Join(table schema.Tabler, on ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bbsPostItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bbsPostItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bbsPostItemDo) Group(cols ...field.Expr) IBbsPostItemDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bbsPostItemDo) Having(conds ...gen.Condition) IBbsPostItemDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bbsPostItemDo) Limit(limit int) IBbsPostItemDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bbsPostItemDo) Offset(offset int) IBbsPostItemDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bbsPostItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBbsPostItemDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bbsPostItemDo) Unscoped() IBbsPostItemDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bbsPostItemDo) Create(values ...*model.BbsPostItem) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bbsPostItemDo) CreateInBatches(values []*model.BbsPostItem, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bbsPostItemDo) Save(values ...*model.BbsPostItem) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bbsPostItemDo) First() (*model.BbsPostItem, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPostItem), nil
	}
}

func (b bbsPostItemDo) Take() (*model.BbsPostItem, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPostItem), nil
	}
}

func (b bbsPostItemDo) Last() (*model.BbsPostItem, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPostItem), nil
	}
}

func (b bbsPostItemDo) Find() ([]*model.BbsPostItem, error) {
	result, err := b.DO.Find()
	return result.([]*model.BbsPostItem), err
}

func (b bbsPostItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BbsPostItem, err error) {
	buf := make([]*model.BbsPostItem, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bbsPostItemDo) FindInBatches(result *[]*model.BbsPostItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bbsPostItemDo) Attrs(attrs ...field.AssignExpr) IBbsPostItemDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bbsPostItemDo) Assign(attrs ...field.AssignExpr) IBbsPostItemDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bbsPostItemDo) Joins(fields ...field.RelationField) IBbsPostItemDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bbsPostItemDo) Preload(fields ...field.RelationField) IBbsPostItemDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bbsPostItemDo) FirstOrInit() (*model.BbsPostItem, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPostItem), nil
	}
}

func (b bbsPostItemDo) FirstOrCreate() (*model.BbsPostItem, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPostItem), nil
	}
}

func (b bbsPostItemDo) FindByPage(offset int, limit int) (result []*model.BbsPostItem, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bbsPostItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bbsPostItemDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bbsPostItemDo) Delete(models ...*model.BbsPostItem) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bbsPostItemDo) withDO(do gen.Dao) *bbsPostItemDo {
	b.DO = *do.(*gen.DO)
	return b
}
