// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/scutrobotlab/rm-search/database/model"
)

func newBbsPost(db *gorm.DB, opts ...gen.DOOption) bbsPost {
	_bbsPost := bbsPost{}

	_bbsPost.bbsPostDo.UseDB(db, opts...)
	_bbsPost.bbsPostDo.UseModel(&model.BbsPost{})

	tableName := _bbsPost.bbsPostDo.TableName()
	_bbsPost.ALL = field.NewAsterisk(tableName)
	_bbsPost.ID = field.NewInt64(tableName, "id")
	_bbsPost.Code = field.NewInt32(tableName, "code")
	_bbsPost.Message = field.NewString(tableName, "message")
	_bbsPost.Success = field.NewBool(tableName, "success")
	_bbsPost.Data = field.NewString(tableName, "data")
	_bbsPost.CreateTime = field.NewTime(tableName, "create_time")
	_bbsPost.UpdateTime = field.NewTime(tableName, "update_time")

	_bbsPost.fillFieldMap()

	return _bbsPost
}

type bbsPost struct {
	bbsPostDo

	ALL        field.Asterisk
	ID         field.Int64
	Code       field.Int32
	Message    field.String
	Success    field.Bool
	Data       field.String
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (b bbsPost) Table(newTableName string) *bbsPost {
	b.bbsPostDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bbsPost) As(alias string) *bbsPost {
	b.bbsPostDo.DO = *(b.bbsPostDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bbsPost) updateTableName(table string) *bbsPost {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.Code = field.NewInt32(table, "code")
	b.Message = field.NewString(table, "message")
	b.Success = field.NewBool(table, "success")
	b.Data = field.NewString(table, "data")
	b.CreateTime = field.NewTime(table, "create_time")
	b.UpdateTime = field.NewTime(table, "update_time")

	b.fillFieldMap()

	return b
}

func (b *bbsPost) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bbsPost) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 7)
	b.fieldMap["id"] = b.ID
	b.fieldMap["code"] = b.Code
	b.fieldMap["message"] = b.Message
	b.fieldMap["success"] = b.Success
	b.fieldMap["data"] = b.Data
	b.fieldMap["create_time"] = b.CreateTime
	b.fieldMap["update_time"] = b.UpdateTime
}

func (b bbsPost) clone(db *gorm.DB) bbsPost {
	b.bbsPostDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bbsPost) replaceDB(db *gorm.DB) bbsPost {
	b.bbsPostDo.ReplaceDB(db)
	return b
}

type bbsPostDo struct{ gen.DO }

type IBbsPostDo interface {
	gen.SubQuery
	Debug() IBbsPostDo
	WithContext(ctx context.Context) IBbsPostDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBbsPostDo
	WriteDB() IBbsPostDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBbsPostDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBbsPostDo
	Not(conds ...gen.Condition) IBbsPostDo
	Or(conds ...gen.Condition) IBbsPostDo
	Select(conds ...field.Expr) IBbsPostDo
	Where(conds ...gen.Condition) IBbsPostDo
	Order(conds ...field.Expr) IBbsPostDo
	Distinct(cols ...field.Expr) IBbsPostDo
	Omit(cols ...field.Expr) IBbsPostDo
	Join(table schema.Tabler, on ...field.Expr) IBbsPostDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBbsPostDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBbsPostDo
	Group(cols ...field.Expr) IBbsPostDo
	Having(conds ...gen.Condition) IBbsPostDo
	Limit(limit int) IBbsPostDo
	Offset(offset int) IBbsPostDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBbsPostDo
	Unscoped() IBbsPostDo
	Create(values ...*model.BbsPost) error
	CreateInBatches(values []*model.BbsPost, batchSize int) error
	Save(values ...*model.BbsPost) error
	First() (*model.BbsPost, error)
	Take() (*model.BbsPost, error)
	Last() (*model.BbsPost, error)
	Find() ([]*model.BbsPost, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BbsPost, err error)
	FindInBatches(result *[]*model.BbsPost, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BbsPost) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBbsPostDo
	Assign(attrs ...field.AssignExpr) IBbsPostDo
	Joins(fields ...field.RelationField) IBbsPostDo
	Preload(fields ...field.RelationField) IBbsPostDo
	FirstOrInit() (*model.BbsPost, error)
	FirstOrCreate() (*model.BbsPost, error)
	FindByPage(offset int, limit int) (result []*model.BbsPost, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBbsPostDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bbsPostDo) Debug() IBbsPostDo {
	return b.withDO(b.DO.Debug())
}

func (b bbsPostDo) WithContext(ctx context.Context) IBbsPostDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bbsPostDo) ReadDB() IBbsPostDo {
	return b.Clauses(dbresolver.Read)
}

func (b bbsPostDo) WriteDB() IBbsPostDo {
	return b.Clauses(dbresolver.Write)
}

func (b bbsPostDo) Session(config *gorm.Session) IBbsPostDo {
	return b.withDO(b.DO.Session(config))
}

func (b bbsPostDo) Clauses(conds ...clause.Expression) IBbsPostDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bbsPostDo) Returning(value interface{}, columns ...string) IBbsPostDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bbsPostDo) Not(conds ...gen.Condition) IBbsPostDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bbsPostDo) Or(conds ...gen.Condition) IBbsPostDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bbsPostDo) Select(conds ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bbsPostDo) Where(conds ...gen.Condition) IBbsPostDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bbsPostDo) Order(conds ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bbsPostDo) Distinct(cols ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bbsPostDo) Omit(cols ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bbsPostDo) Join(table schema.Tabler, on ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bbsPostDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bbsPostDo) RightJoin(table schema.Tabler, on ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bbsPostDo) Group(cols ...field.Expr) IBbsPostDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bbsPostDo) Having(conds ...gen.Condition) IBbsPostDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bbsPostDo) Limit(limit int) IBbsPostDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bbsPostDo) Offset(offset int) IBbsPostDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bbsPostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBbsPostDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bbsPostDo) Unscoped() IBbsPostDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bbsPostDo) Create(values ...*model.BbsPost) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bbsPostDo) CreateInBatches(values []*model.BbsPost, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bbsPostDo) Save(values ...*model.BbsPost) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bbsPostDo) First() (*model.BbsPost, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPost), nil
	}
}

func (b bbsPostDo) Take() (*model.BbsPost, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPost), nil
	}
}

func (b bbsPostDo) Last() (*model.BbsPost, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPost), nil
	}
}

func (b bbsPostDo) Find() ([]*model.BbsPost, error) {
	result, err := b.DO.Find()
	return result.([]*model.BbsPost), err
}

func (b bbsPostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BbsPost, err error) {
	buf := make([]*model.BbsPost, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bbsPostDo) FindInBatches(result *[]*model.BbsPost, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bbsPostDo) Attrs(attrs ...field.AssignExpr) IBbsPostDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bbsPostDo) Assign(attrs ...field.AssignExpr) IBbsPostDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bbsPostDo) Joins(fields ...field.RelationField) IBbsPostDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bbsPostDo) Preload(fields ...field.RelationField) IBbsPostDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bbsPostDo) FirstOrInit() (*model.BbsPost, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPost), nil
	}
}

func (b bbsPostDo) FirstOrCreate() (*model.BbsPost, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BbsPost), nil
	}
}

func (b bbsPostDo) FindByPage(offset int, limit int) (result []*model.BbsPost, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bbsPostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bbsPostDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bbsPostDo) Delete(models ...*model.BbsPost) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bbsPostDo) withDO(do gen.Dao) *bbsPostDo {
	b.DO = *do.(*gen.DO)
	return b
}
