// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Announce    *announce
	Attachment  *attachment
	BbsPost     *bbsPost
	BbsPostItem *bbsPostItem
	SearchLog   *searchLog
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Announce = &Q.Announce
	Attachment = &Q.Attachment
	BbsPost = &Q.BbsPost
	BbsPostItem = &Q.BbsPostItem
	SearchLog = &Q.SearchLog
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Announce:    newAnnounce(db, opts...),
		Attachment:  newAttachment(db, opts...),
		BbsPost:     newBbsPost(db, opts...),
		BbsPostItem: newBbsPostItem(db, opts...),
		SearchLog:   newSearchLog(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Announce    announce
	Attachment  attachment
	BbsPost     bbsPost
	BbsPostItem bbsPostItem
	SearchLog   searchLog
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Announce:    q.Announce.clone(db),
		Attachment:  q.Attachment.clone(db),
		BbsPost:     q.BbsPost.clone(db),
		BbsPostItem: q.BbsPostItem.clone(db),
		SearchLog:   q.SearchLog.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Announce:    q.Announce.replaceDB(db),
		Attachment:  q.Attachment.replaceDB(db),
		BbsPost:     q.BbsPost.replaceDB(db),
		BbsPostItem: q.BbsPostItem.replaceDB(db),
		SearchLog:   q.SearchLog.replaceDB(db),
	}
}

type queryCtx struct {
	Announce    IAnnounceDo
	Attachment  IAttachmentDo
	BbsPost     IBbsPostDo
	BbsPostItem IBbsPostItemDo
	SearchLog   ISearchLogDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Announce:    q.Announce.WithContext(ctx),
		Attachment:  q.Attachment.WithContext(ctx),
		BbsPost:     q.BbsPost.WithContext(ctx),
		BbsPostItem: q.BbsPostItem.WithContext(ctx),
		SearchLog:   q.SearchLog.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
