// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/scutrobotlab/rm-search/database/model"
)

func newPostResp(db *gorm.DB, opts ...gen.DOOption) postResp {
	_postResp := postResp{}

	_postResp.postRespDo.UseDB(db, opts...)
	_postResp.postRespDo.UseModel(&model.PostResp{})

	tableName := _postResp.postRespDo.TableName()
	_postResp.ALL = field.NewAsterisk(tableName)
	_postResp.ID = field.NewInt64(tableName, "id")
	_postResp.Code = field.NewInt32(tableName, "code")
	_postResp.Message = field.NewString(tableName, "message")
	_postResp.Success = field.NewBool(tableName, "success")
	_postResp.Data = field.NewString(tableName, "data")
	_postResp.CreateTime = field.NewTime(tableName, "create_time")
	_postResp.UpdateTime = field.NewTime(tableName, "update_time")

	_postResp.fillFieldMap()

	return _postResp
}

type postResp struct {
	postRespDo

	ALL        field.Asterisk
	ID         field.Int64  // 帖子ID
	Code       field.Int32  // 状态码
	Message    field.String // 状态信息
	Success    field.Bool   // 是否成功
	Data       field.String // 数据
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (p postResp) Table(newTableName string) *postResp {
	p.postRespDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p postResp) As(alias string) *postResp {
	p.postRespDo.DO = *(p.postRespDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *postResp) updateTableName(table string) *postResp {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Code = field.NewInt32(table, "code")
	p.Message = field.NewString(table, "message")
	p.Success = field.NewBool(table, "success")
	p.Data = field.NewString(table, "data")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateTime = field.NewTime(table, "update_time")

	p.fillFieldMap()

	return p
}

func (p *postResp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *postResp) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["code"] = p.Code
	p.fieldMap["message"] = p.Message
	p.fieldMap["success"] = p.Success
	p.fieldMap["data"] = p.Data
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
}

func (p postResp) clone(db *gorm.DB) postResp {
	p.postRespDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p postResp) replaceDB(db *gorm.DB) postResp {
	p.postRespDo.ReplaceDB(db)
	return p
}

type postRespDo struct{ gen.DO }

type IPostRespDo interface {
	gen.SubQuery
	Debug() IPostRespDo
	WithContext(ctx context.Context) IPostRespDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPostRespDo
	WriteDB() IPostRespDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPostRespDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPostRespDo
	Not(conds ...gen.Condition) IPostRespDo
	Or(conds ...gen.Condition) IPostRespDo
	Select(conds ...field.Expr) IPostRespDo
	Where(conds ...gen.Condition) IPostRespDo
	Order(conds ...field.Expr) IPostRespDo
	Distinct(cols ...field.Expr) IPostRespDo
	Omit(cols ...field.Expr) IPostRespDo
	Join(table schema.Tabler, on ...field.Expr) IPostRespDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPostRespDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPostRespDo
	Group(cols ...field.Expr) IPostRespDo
	Having(conds ...gen.Condition) IPostRespDo
	Limit(limit int) IPostRespDo
	Offset(offset int) IPostRespDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPostRespDo
	Unscoped() IPostRespDo
	Create(values ...*model.PostResp) error
	CreateInBatches(values []*model.PostResp, batchSize int) error
	Save(values ...*model.PostResp) error
	First() (*model.PostResp, error)
	Take() (*model.PostResp, error)
	Last() (*model.PostResp, error)
	Find() ([]*model.PostResp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PostResp, err error)
	FindInBatches(result *[]*model.PostResp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PostResp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPostRespDo
	Assign(attrs ...field.AssignExpr) IPostRespDo
	Joins(fields ...field.RelationField) IPostRespDo
	Preload(fields ...field.RelationField) IPostRespDo
	FirstOrInit() (*model.PostResp, error)
	FirstOrCreate() (*model.PostResp, error)
	FindByPage(offset int, limit int) (result []*model.PostResp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPostRespDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p postRespDo) Debug() IPostRespDo {
	return p.withDO(p.DO.Debug())
}

func (p postRespDo) WithContext(ctx context.Context) IPostRespDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p postRespDo) ReadDB() IPostRespDo {
	return p.Clauses(dbresolver.Read)
}

func (p postRespDo) WriteDB() IPostRespDo {
	return p.Clauses(dbresolver.Write)
}

func (p postRespDo) Session(config *gorm.Session) IPostRespDo {
	return p.withDO(p.DO.Session(config))
}

func (p postRespDo) Clauses(conds ...clause.Expression) IPostRespDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p postRespDo) Returning(value interface{}, columns ...string) IPostRespDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p postRespDo) Not(conds ...gen.Condition) IPostRespDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p postRespDo) Or(conds ...gen.Condition) IPostRespDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p postRespDo) Select(conds ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p postRespDo) Where(conds ...gen.Condition) IPostRespDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p postRespDo) Order(conds ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p postRespDo) Distinct(cols ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p postRespDo) Omit(cols ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p postRespDo) Join(table schema.Tabler, on ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p postRespDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p postRespDo) RightJoin(table schema.Tabler, on ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p postRespDo) Group(cols ...field.Expr) IPostRespDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p postRespDo) Having(conds ...gen.Condition) IPostRespDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p postRespDo) Limit(limit int) IPostRespDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p postRespDo) Offset(offset int) IPostRespDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p postRespDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPostRespDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p postRespDo) Unscoped() IPostRespDo {
	return p.withDO(p.DO.Unscoped())
}

func (p postRespDo) Create(values ...*model.PostResp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p postRespDo) CreateInBatches(values []*model.PostResp, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p postRespDo) Save(values ...*model.PostResp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p postRespDo) First() (*model.PostResp, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostResp), nil
	}
}

func (p postRespDo) Take() (*model.PostResp, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostResp), nil
	}
}

func (p postRespDo) Last() (*model.PostResp, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostResp), nil
	}
}

func (p postRespDo) Find() ([]*model.PostResp, error) {
	result, err := p.DO.Find()
	return result.([]*model.PostResp), err
}

func (p postRespDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PostResp, err error) {
	buf := make([]*model.PostResp, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p postRespDo) FindInBatches(result *[]*model.PostResp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p postRespDo) Attrs(attrs ...field.AssignExpr) IPostRespDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p postRespDo) Assign(attrs ...field.AssignExpr) IPostRespDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p postRespDo) Joins(fields ...field.RelationField) IPostRespDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p postRespDo) Preload(fields ...field.RelationField) IPostRespDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p postRespDo) FirstOrInit() (*model.PostResp, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostResp), nil
	}
}

func (p postRespDo) FirstOrCreate() (*model.PostResp, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostResp), nil
	}
}

func (p postRespDo) FindByPage(offset int, limit int) (result []*model.PostResp, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p postRespDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p postRespDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p postRespDo) Delete(models ...*model.PostResp) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *postRespDo) withDO(do gen.Dao) *postRespDo {
	p.DO = *do.(*gen.DO)
	return p
}
