// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/scutrobotlab/rm-search/database/model"
)

func newSearchLog(db *gorm.DB, opts ...gen.DOOption) searchLog {
	_searchLog := searchLog{}

	_searchLog.searchLogDo.UseDB(db, opts...)
	_searchLog.searchLogDo.UseModel(&model.SearchLog{})

	tableName := _searchLog.searchLogDo.TableName()
	_searchLog.ALL = field.NewAsterisk(tableName)
	_searchLog.ID = field.NewInt64(tableName, "id")
	_searchLog.RemoteIP = field.NewString(tableName, "remote_ip")
	_searchLog.UserAgent = field.NewString(tableName, "user_agent")
	_searchLog.RequestBody = field.NewString(tableName, "request_body")
	_searchLog.RequestLength = field.NewInt32(tableName, "request_length")
	_searchLog.Query = field.NewString(tableName, "query")
	_searchLog.Status = field.NewInt32(tableName, "status")
	_searchLog.ResponseBody = field.NewString(tableName, "response_body")
	_searchLog.ResponseLength = field.NewInt32(tableName, "response_length")
	_searchLog.Latency = field.NewInt32(tableName, "latency")
	_searchLog.CreateTime = field.NewTime(tableName, "create_time")
	_searchLog.UpdateTime = field.NewTime(tableName, "update_time")

	_searchLog.fillFieldMap()

	return _searchLog
}

type searchLog struct {
	searchLogDo

	ALL            field.Asterisk
	ID             field.Int64
	RemoteIP       field.String
	UserAgent      field.String
	RequestBody    field.String
	RequestLength  field.Int32
	Query          field.String
	Status         field.Int32
	ResponseBody   field.String
	ResponseLength field.Int32
	Latency        field.Int32
	CreateTime     field.Time
	UpdateTime     field.Time

	fieldMap map[string]field.Expr
}

func (s searchLog) Table(newTableName string) *searchLog {
	s.searchLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s searchLog) As(alias string) *searchLog {
	s.searchLogDo.DO = *(s.searchLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *searchLog) updateTableName(table string) *searchLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.RemoteIP = field.NewString(table, "remote_ip")
	s.UserAgent = field.NewString(table, "user_agent")
	s.RequestBody = field.NewString(table, "request_body")
	s.RequestLength = field.NewInt32(table, "request_length")
	s.Query = field.NewString(table, "query")
	s.Status = field.NewInt32(table, "status")
	s.ResponseBody = field.NewString(table, "response_body")
	s.ResponseLength = field.NewInt32(table, "response_length")
	s.Latency = field.NewInt32(table, "latency")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *searchLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *searchLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["remote_ip"] = s.RemoteIP
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["request_body"] = s.RequestBody
	s.fieldMap["request_length"] = s.RequestLength
	s.fieldMap["query"] = s.Query
	s.fieldMap["status"] = s.Status
	s.fieldMap["response_body"] = s.ResponseBody
	s.fieldMap["response_length"] = s.ResponseLength
	s.fieldMap["latency"] = s.Latency
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s searchLog) clone(db *gorm.DB) searchLog {
	s.searchLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s searchLog) replaceDB(db *gorm.DB) searchLog {
	s.searchLogDo.ReplaceDB(db)
	return s
}

type searchLogDo struct{ gen.DO }

type ISearchLogDo interface {
	gen.SubQuery
	Debug() ISearchLogDo
	WithContext(ctx context.Context) ISearchLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISearchLogDo
	WriteDB() ISearchLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISearchLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISearchLogDo
	Not(conds ...gen.Condition) ISearchLogDo
	Or(conds ...gen.Condition) ISearchLogDo
	Select(conds ...field.Expr) ISearchLogDo
	Where(conds ...gen.Condition) ISearchLogDo
	Order(conds ...field.Expr) ISearchLogDo
	Distinct(cols ...field.Expr) ISearchLogDo
	Omit(cols ...field.Expr) ISearchLogDo
	Join(table schema.Tabler, on ...field.Expr) ISearchLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISearchLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISearchLogDo
	Group(cols ...field.Expr) ISearchLogDo
	Having(conds ...gen.Condition) ISearchLogDo
	Limit(limit int) ISearchLogDo
	Offset(offset int) ISearchLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchLogDo
	Unscoped() ISearchLogDo
	Create(values ...*model.SearchLog) error
	CreateInBatches(values []*model.SearchLog, batchSize int) error
	Save(values ...*model.SearchLog) error
	First() (*model.SearchLog, error)
	Take() (*model.SearchLog, error)
	Last() (*model.SearchLog, error)
	Find() ([]*model.SearchLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SearchLog, err error)
	FindInBatches(result *[]*model.SearchLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SearchLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISearchLogDo
	Assign(attrs ...field.AssignExpr) ISearchLogDo
	Joins(fields ...field.RelationField) ISearchLogDo
	Preload(fields ...field.RelationField) ISearchLogDo
	FirstOrInit() (*model.SearchLog, error)
	FirstOrCreate() (*model.SearchLog, error)
	FindByPage(offset int, limit int) (result []*model.SearchLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISearchLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s searchLogDo) Debug() ISearchLogDo {
	return s.withDO(s.DO.Debug())
}

func (s searchLogDo) WithContext(ctx context.Context) ISearchLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s searchLogDo) ReadDB() ISearchLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s searchLogDo) WriteDB() ISearchLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s searchLogDo) Session(config *gorm.Session) ISearchLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s searchLogDo) Clauses(conds ...clause.Expression) ISearchLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s searchLogDo) Returning(value interface{}, columns ...string) ISearchLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s searchLogDo) Not(conds ...gen.Condition) ISearchLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s searchLogDo) Or(conds ...gen.Condition) ISearchLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s searchLogDo) Select(conds ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s searchLogDo) Where(conds ...gen.Condition) ISearchLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s searchLogDo) Order(conds ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s searchLogDo) Distinct(cols ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s searchLogDo) Omit(cols ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s searchLogDo) Join(table schema.Tabler, on ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s searchLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s searchLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s searchLogDo) Group(cols ...field.Expr) ISearchLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s searchLogDo) Having(conds ...gen.Condition) ISearchLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s searchLogDo) Limit(limit int) ISearchLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s searchLogDo) Offset(offset int) ISearchLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s searchLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s searchLogDo) Unscoped() ISearchLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s searchLogDo) Create(values ...*model.SearchLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s searchLogDo) CreateInBatches(values []*model.SearchLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s searchLogDo) Save(values ...*model.SearchLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s searchLogDo) First() (*model.SearchLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchLog), nil
	}
}

func (s searchLogDo) Take() (*model.SearchLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchLog), nil
	}
}

func (s searchLogDo) Last() (*model.SearchLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchLog), nil
	}
}

func (s searchLogDo) Find() ([]*model.SearchLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SearchLog), err
}

func (s searchLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SearchLog, err error) {
	buf := make([]*model.SearchLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s searchLogDo) FindInBatches(result *[]*model.SearchLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s searchLogDo) Attrs(attrs ...field.AssignExpr) ISearchLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s searchLogDo) Assign(attrs ...field.AssignExpr) ISearchLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s searchLogDo) Joins(fields ...field.RelationField) ISearchLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s searchLogDo) Preload(fields ...field.RelationField) ISearchLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s searchLogDo) FirstOrInit() (*model.SearchLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchLog), nil
	}
}

func (s searchLogDo) FirstOrCreate() (*model.SearchLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchLog), nil
	}
}

func (s searchLogDo) FindByPage(offset int, limit int) (result []*model.SearchLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s searchLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s searchLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s searchLogDo) Delete(models ...*model.SearchLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *searchLogDo) withDO(do gen.Dao) *searchLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
