-- rm-search schema for PostgreSQL.
-- Applied by the deploy stack on first boot (POSTGRES_DB=rm_search);
-- for manual setup run inside the target database.

CREATE TABLE IF NOT EXISTS bbs_post
(
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        integer      NOT NULL DEFAULT 0,
    message     varchar(256) NOT NULL DEFAULT '',
    success     boolean      NOT NULL DEFAULT FALSE,
    data        jsonb        NOT NULL,
    create_time timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_bbs_post_code ON bbs_post (code);
CREATE INDEX IF NOT EXISTS idx_bbs_post_create_time ON bbs_post (create_time);
CREATE INDEX IF NOT EXISTS idx_bbs_post_update_time ON bbs_post (update_time);
COMMENT ON TABLE bbs_post IS '论坛帖子';

CREATE TABLE IF NOT EXISTS announce
(
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    found       boolean      NOT NULL DEFAULT FALSE,
    title       varchar(256) NOT NULL DEFAULT '',
    date        date         NOT NULL DEFAULT DATE '0001-01-01',
    context     text         NOT NULL,
    content     text         NOT NULL,
    attachments jsonb        NOT NULL,
    create_time timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_announce_found ON announce (found);
CREATE INDEX IF NOT EXISTS idx_announce_date ON announce (date);
COMMENT ON TABLE announce IS '公告';

CREATE TABLE IF NOT EXISTS attachment
(
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           varchar(512) NOT NULL DEFAULT '',
    name          varchar(256) NOT NULL DEFAULT '',
    size          bigint       NOT NULL DEFAULT 0,
    type          varchar(64)  NOT NULL DEFAULT '',
    sha256        char(64)     NOT NULL DEFAULT '',
    content       text         NOT NULL,
    last_modified bigint       NOT NULL DEFAULT 0,
    create_time   timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time   timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_attachment_url ON attachment (url);
CREATE UNIQUE INDEX IF NOT EXISTS idx_attachment_sha256 ON attachment (sha256);
COMMENT ON TABLE attachment IS '附件';

CREATE TABLE IF NOT EXISTS search_log
(
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remote_ip       char(39)     NOT NULL DEFAULT '',
    user_agent      varchar(512) NOT NULL DEFAULT '',
    request_body    text         NOT NULL,
    request_length  integer      NOT NULL DEFAULT 0,
    query           varchar(256) NOT NULL DEFAULT '',
    status          integer      NOT NULL DEFAULT 0,
    response_body   text         NOT NULL,
    response_length integer      NOT NULL DEFAULT 0,
    latency         integer      NOT NULL DEFAULT 0,
    create_time     timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time     timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_search_log_remote_ip ON search_log (remote_ip);
CREATE INDEX IF NOT EXISTS idx_search_log_request_length ON search_log (request_length);
CREATE INDEX IF NOT EXISTS idx_search_log_query ON search_log (query);
CREATE INDEX IF NOT EXISTS idx_search_log_status ON search_log (status);
CREATE INDEX IF NOT EXISTS idx_search_log_response_length ON search_log (response_length);
CREATE INDEX IF NOT EXISTS idx_search_log_latency ON search_log (latency);
CREATE INDEX IF NOT EXISTS idx_search_log_create_time ON search_log (create_time);
COMMENT ON TABLE search_log IS '搜索日志';

-- Watermarks of the scheduled newest-first/backfill crawler (single row, id=1).
CREATE TABLE IF NOT EXISTS crawl_state
(
    id                integer      PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    newest_crawled_id bigint       NOT NULL DEFAULT 0,
    oldest_crawled_id bigint       NOT NULL DEFAULT 9223372036854775807,
    backfill_done     boolean      NOT NULL DEFAULT FALSE,
    create_time       timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time       timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
COMMENT ON TABLE crawl_state IS '定时爬取水位';

-- PostgreSQL has no ON UPDATE CURRENT_TIMESTAMP; emulate it so
-- update_time keeps the semantics the MySQL schema had.
CREATE OR REPLACE FUNCTION set_update_time() RETURNS trigger AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP(3);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['bbs_post', 'announce', 'attachment', 'search_log', 'crawl_state'] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_update ON %I', t, t);
        EXECUTE format('CREATE TRIGGER trg_%s_update BEFORE UPDATE ON %I
                        FOR EACH ROW EXECUTE FUNCTION set_update_time()', t, t);
    END LOOP;
END;
$$;
